# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        [ROLE_MEMBER, ROLE_ADMIN]
        ROLE_INVESTOR:    [ROLE_INVESTOR, ROLE_ADMIN]
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_SUPER_ADMIN]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:             fos_userbundle
                login_path:           fos_user_security_login
                check_path:           fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /
                #target_path_parameter:          _target_path
                #use_referer:                    false

            logout:
                path:     fos_user_security_logout
                target:   fos_user_security_login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activate, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activate/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/member/, role: ROLE_MEMBER }
        - { path: ^/csadmin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
