<?php

namespace Cornershort\MLMappBundle\Repository;

/**
 * LevelInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
